id: kinfocenter
version: 6.6.4
about: Plasma kinfocenter

configure: >-
  -DCMAKE_BUILD_TYPE=Release
  -DBUILD_TESTING=OFF
  -Wno-dev

depends:
  - glu
  - mesa
  - desktop-file-utils
build-depends:
  - extra-cmake-modules
  - kdoctools
  - plasma-framework
  - kcmutils
sources:
  - https://download.kde.org/stable/plasma/%{version}/%{id}-%{version}.tar.xz
