id: strace
version: 7.0
about: A diagnostic, debugging and instructional userspace tracer

run-autogen: false
seperate-build-dir: false

environ:
    - CC=clang
    - CXX=clang++

configure: >-
  --enable-mpers=no

sources:
    - https://github.com/strace/strace/releases/download/v%{version}/strace-%{version}.tar.xz

depends:
    - perl
    - llvm-runtime

build-depends:
    - llvm
