id: pam
version: 1.7.2
about: Pluggable Authentication Modules library

configure: >-
  -D docs=disabled

depends:
  - glibc
  - libxcrypt

sources:
  - https://github.com/linux-pam/linux-pam/releases/download/v%{version}/Linux-PAM-%{version}.tar.xz

post-script: |-
  chmod 4755 "%{install-root}"/usr/bin/unix_chkpwd

  install -v -D -m 0755 /dev/stdin %{install-root}%{libdir}/tmpfiles.d/pam.conf << EOF
  d /run/faillock 0755 root root -
  EOF