id: adwaita-icon-theme
version: 50.0
about: Adwaita Icon Theme package contains an icon theme for Gtk+ 3 applications

script: |-
  meson setup --prefix=%{prefix} %{build-dir}
  ninja -C %{build-dir}
  DESTDIR=%{install-root} ninja -C %{build-dir} install

depends:
  - hicolor-icon-theme

sources:
  - https://download.gnome.org/sources/adwaita-icon-theme/%{version:1}/adwaita-icon-theme-%{version}.tar.xz
