id: cargo-c
version: 0.10.22
release: 2
about:  cargo subcommand to build and install C-ABI compatible dynamic and static libraries

environ:
  - LIBSSH2_SYS_USE_PKG_CONFIG=1
  - LIBSQLITE3_SYS_USE_PKG_CONFIG=1

post-script: |-
  install -D -v -m 755 target/release/cargo-{capi,cbuild,cinstall,ctest} -t %{install-root}%{bindir}

depends:
  - rustc
  - libssh

sources:
  - https://github.com/lu-zero/cargo-c/archive/v%{version}/cargo-c-%{version}.tar.gz
