id: dbus
version: 1.16.2
about: A message bus system, a simple way for applications to talk to one another

build-type: meson

configure: >-
  -D modular_tests=disabled

build-depends:
  - python
  - meson
  - ninja

depends:
  - expat
  - systemd

sources:
  - https://dbus.freedesktop.org/releases/dbus/dbus-%{version}.tar.xz
