id: touchegg
version: 2.0.18
about: Multitouch gesture recognizer

configure: >-
  -D CMAKE_POLICY_VERSION_MINIMUM=3.5
  -Wno-dev

post-script: |-
  install -vDm 0644 /dev/stdin %{install-root}/%{datadir}/touchegg/touchegg.conf << "EOF"
  <touchégg>
    <settings>
      <property name="animation_delay">150</property>
      <property name="action_execute_threshold">20</property>
      <property name="color">auto</property>
      <property name="borderColor">auto</property>
    </settings>

    <application name="All">

      <gesture type="SWIPE" fingers="3" direction="LEFT">
        <action type="SEND_KEYS">
          <modifiers>Control_L Alt_L</modifiers>
          <keys>Right</keys>
        </action>
      </gesture>

      <gesture type="SWIPE" fingers="3" direction="RIGHT">
        <action type="SEND_KEYS">
          <modifiers>Control_L Alt_L</modifiers>
          <keys>Left</keys>
        </action>
      </gesture>

      <gesture type="SWIPE" fingers="3" direction="UP">
        <action type="SEND_KEYS">
          <modifiers>Alt_L</modifiers>
          <keys>Tab</keys>
        </action>
      </gesture>

      <gesture type="SWIPE" fingers="3" direction="DOWN">
        <action type="MINIMIZE_WINDOW">
        </action>
      </gesture>

      <gesture type="PINCH" fingers="3" direction="IN">
        <action type="CLOSE_WINDOW">
        </action>
      </gesture>

      <gesture type="PINCH" fingers="3" direction="OUT">
        <action type="MAXIMIZE_RESTORE_WINDOW">
        </action>
      </gesture>

    </application>
  </touchégg>
  EOF

depends:
  - gtk3
  - libinput
  - libx11
  - systemd
  - pugixml

build-depends:
  - cmake

sources:
  - toughegg-%{version}.tar.gz::https://github.com/JoseExposito/touchegg/archive/refs/tags/%{version}.tar.gz
