id: swayfx
version: 0.5.3
about: Sway, but with eye candy!

pre-script: |-
  sed -i "s/branch \\\'@1@\\\'/rlxos/g" meson.build
post-script: |-
  install -v -D -m 0644 /dev/stdin %{install-root}%{sysconfdir}/sway/config.d/50-systemd-user.conf << "EOF"
  exec systemctl --user set-environment XDG_CURRENT_DESKTOP=sway
  exec systemctl --user import-environment DISPLAY \
                                           SWAYSOCK \
                                           WAYLAND_DISPLAY \
                                           XDG_CURRENT_DESKTOP

  exec hash dbus-update-activation-environment 2>/dev/null && \
       dbus-update-activation-environment --systemd DISPLAY \
                                                    SWAYSOCK \
                                                    XDG_CURRENT_DESKTOP=sway \
                                                    WAYLAND_DISPLAY

  EOF

  install -v -D -m 0644 /dev/stdin %{install-root}%{datadir}/xdg-desktop-portal/sway-portals.conf << "EOF"
  [preferred]
  default=gtk
  org.freedesktop.impl.portal.ScreenCast=wlr
  org.freedesktop.impl.portal.Screenshot=wlr
  EOF

  install -v -D -m 0644 LICENSE -t %{install-root}%{datadir}/doc/%{id}/

configure: >-
  -D sd-bus-provider=libsystemd
  -D werror=false
  -D b_ndebug=true

depends:
  - cairo
  - gdk-pixbuf
  - libevdev
  - libinput
  - json-c
  - scenefx
  - systemd
  - wayland
  - wlroots
  - libxcb
  - libxkbcommon
  - pango
  - pcre
  - seatd

build-depends:
  - meson
  - ninja
  - scdoc
  - setconf
  - wayland-protocols

sources:
  - swayfx-%{version}.tar.gz::https://github.com/WillPower3309/swayfx/archive/refs/tags/%{version}.tar.gz
