id: man-db
version: 2.13.1
about: Programs for finding and viewing man pages

depends:
  - bash
  - gdbm
  - groff
  - less
  - libpipeline
  - zlib
sources:
  - https://download-mirror.savannah.gnu.org/releases/man-db/man-db-%{version}.tar.xz

configure: >-
  --disable-setuid
  --enable-cache-owner=bin
