id: libvdpau
version: 1.5
about: A library which implements the VDPAU library

depends:
  - libx11
sources:
  - https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/%{version}/libvdpau-%{version}.tar.bz2
