id: conky-manager
version: 2.7
about: GUI for managing conky config files with options to browse and edit themes

script: |-
  make
  make DESTDIR=%{install-root} install

depends:
  - conky
  - cairo
  - desktop-file-utils
  - gtk3
  - imagemagick
  - json-glib
  - libgee
  - p7zip
  - rsync
  - psmisc
build-depends:
  - vala
sources:
  - conky-manager-%{version}.tar.gz::https://github.com/teejee2008/conky-manager/archive/refs/tags/v%{version}.tar.gz
