CFLAGS		+= -fPIC -std=c99 -ffreestanding -nostdinc
LDFLAGS		+= -nostdlib -Wl,-Bsymbolic-functions

CPPFLAGS	+= -D_XOPEN_SOURCE=700
CPPFLAGS	+= -I ${.TOPDIR}/arch/${TARGET_ARCH}
CPPFLAGS	+= -I ${.TOPDIR}/arch/generic
CPPFLAGS	+= -I ${.TOPDIR}/lib/libc/include
CPPFLAGS	+= -I ${.TOPDIR}/lib/libc/internal
CPPFLAGS	+= -I ${.BUILDDIR}/include/generated
CPPFLAGS	+= -I ${.TOPDIR}/include
