id: gcr
version: 3.41.2
about: Libraries used for displaying certificates and accessing key stores

pre-script: |-
  sed -i "s:\"/desktop:\"/org:" schema/*.xml

configure: >-
  -D gtk_doc=false

depends:
  - glib
  - libgcrypt
  - p11-kit
  - gnupg
  - gtk3
  - libxslt

build-depends:
  - gobject-introspection
  - vala
  - gtk-doc
  - openssh

sources:
  - https://download.gnome.org/sources/gcr/%{version:2}/gcr-%{version}.tar.xz
