id: kjs
merge: [external/kf5.inc]
about: KF5 kjs

depends:
  - qt
  - pcre
build-depends:
  - extra-cmake-modules
  - kdoctools

sources:
  - https://download.kde.org/stable/frameworks/%{version:2}/portingAids/%{id}-%{version}.tar.xz
