id: selftest
version: 0.0.1
about: rlxos self test utility
release: 0
depends:
- external/findutils
- external/grep
- external/gawk
script: install -vDm0755 /external/selftest.sh %{install-root}/usr/bin/selftest
