id: libxfont2
version: 2.0.7
about: xorg library libXfont2

sources:
  - https://www.x.org/pub/individual/lib/libXfont2-%{version}.tar.xz

depends:
  - freetype
  - libfontenc

build-depends:
  - xorgproto
  - util-macros
  - xtrans
