id: python-gobject
version: 3.56.2
about: Python bindings to the GObject class from GLib

depends:
  - gobject-introspection
  - python-cairo
sources:
  - https://download.gnome.org/sources/pygobject/%{version:2}/pygobject-%{version}.tar.gz

pre-script: mv -v tests/test_gdbus.py{,.nouse}
