id: xcb-util-errors
version: 1.0.1
about: XCB errors library

sources:
  - https://xorg.freedesktop.org/archive/individual/lib/xcb-util-errors-%{version}.tar.xz
depends:
  - libxcb
build-depends:
  - xorgproto