id: gnu-efi
version: 4.0.4
about: Develop EFI applications using the GNU toolchain and the EFI development environment

script: |
  export LDFLAGS="${LDFLAGS//-Wl/}"
  export LDFLAGS="${LDFLAGS//,/ }"
  export CFLAGS="-O2"
  make CC=clang
  make INSTALLROOT="%{install-root}" PREFIX=%{prefix} install

depends:
  - glibc

build-depends:
  - llvm

sources:
  - gnu-efi-%{version}.tar.bz2::https://github.com/ncroxon/gnu-efi/archive/refs/tags/%{version}.tar.gz
