id: webp-pixbuf-loader
version: 0.2.7
about: WebM GDK Pixbuf loader library

depends:
  - gdk-pixbuf
  - libwebp
sources:
  - https://github.com/aruiz/webp-pixbuf-loader/archive/%{version}/webp-pixbuf-loader-%{version}.tar.gz
