id: eglexternalplatform
version: 1.2.1
about: EGL External Platform interface

configure: >-
  --includedir %{prefix}/include/EGL

depends:
  - libglvnd

sources:
  - eglexternalplatform-%{version}.tar.gz::https://github.com/NVIDIA/eglexternalplatform/archive/refs/tags/%{version}.tar.gz
