id: kuserfeedback
version: 6.26.0
about: Framework for collecting user feedback for applications via telemetry and surveys

configure: >-
  -DCMAKE_BUILD_TYPE=Release
  -DBUILD_TESTING=OFF
  -Wno-dev

depends:
  - qt
build-depends:
  - extra-cmake-modules
sources:
  - https://download.kde.org/stable/kuserfeedback/kuserfeedback-%{version}.tar.xz
