id: ristretto
version: 0.14.0
about: A fast and lightweight picture viewer for Xfce

variables:
  run-autogen: false

depends:
  - libexif
  - libxfce4ui
  - xfconf
  - exo

build-depends:
  - intltool
  - file

sources:
  - https://archive.xfce.org/src/apps/ristretto/%{version:2}/ristretto-%{version}.tar.xz
