id: gdk-pixbuf
version: 2.44.6
about: Package is a toolkit for image loading and pixel buffer manipulation

configure: >
  --buildtype=release
  -D man=false
  -D installed_tests=false
  -D glycin=disabled

integration: |-
  gdk-pixbuf-query-loaders --update-cache

sources:
  - https://download.gnome.org/sources/gdk-pixbuf/%{version:2}/gdk-pixbuf-%{version}.tar.xz

build-depends:
  - gobject-introspection
  - gtk-doc

depends:
  - glib
  - libjpeg-turbo
  - libpng
  - shared-mime-info
  - libtiff
