id: docbook-xml
version: 4.5
about: Package contains document type definitions for verification of XML data files against the DocBook rule set

build-dir: "."
script: |
  install -v -d -m 755 %{install-root}/usr/share/xml/docbook/xml-dtd-5.1
  install -v -d -m 755 %{install-root}/etc/xml
  cp -v -a -f docbook.cat *.dtd ent/ *.mod %{install-root}/usr/share/xml/docbook/xml-dtd-5.1

  xmlcatalog --noout --create %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//DTD DocBook XML V5.1//EN" \
      "http://www.oasis-open.org/docbook/xml/5.1/docbookx.dtd" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//DTD DocBook XML CALS Table Model V5.1//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/calstblx.dtd" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//DTD XML Exchange Table Model 19990315//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/soextblx.dtd" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//ELEMENTS DocBook XML Information Pool V5.1//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/dbpoolx.mod" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public"   \
      "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V5.1//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/dbhierx.mod" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//ELEMENTS DocBook XML HTML Tables V5.1//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/htmltblx.mod" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//ENTITIES DocBook XML Notations V5.1//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/dbnotnx.mod" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public" \
      "-//OASIS//ENTITIES DocBook XML Character Entities V5.1//EN"  \
    "file:///usr/share/xml/docbook/xml-dtd-5.1/dbcentx.mod"  \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "public"  \
      "-//OASIS//ENTITIES DocBook XML Additional General Entities V5.1//EN"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1/dbgenent.mod" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --add "rewriteSystem" \
      "http://www.oasis-open.org/docbook/xml/5.1"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1" \
      %{install-root}/etc/xml/docbook


  xmlcatalog --noout --add "rewriteURI" \
      "http://www.oasis-open.org/docbook/xml/5.1"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1" \
      %{install-root}/etc/xml/docbook

  xmlcatalog --noout --create %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegatePublic"  "-//OASIS//ENTITIES DocBook XML" \
      "file:///etc/xml/docbook" \
      %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegatePublic"  \
      "-//OASIS//DTD DocBook XML" \
      "file:///etc/xml/docbook"  \
      %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegateSystem"  \
      "http://www.oasis-open.org/docbook/" \
      "file:///etc/xml/docbook"  \
      %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegateURI"  \
      "http://www.oasis-open.org/docbook/" \
      "file:///etc/xml/docbook"  \
      %{install-root}/etc/xml/catalog



  for DTDVERSION in 4.1.2 4.2 4.3 4.4 ; do
    xmlcatalog --noout --add "public" \
      "-//OASIS//DTD DocBook XML V$DTDVERSION//EN"  \
      "http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
      %{install-root}/etc/xml/docbook

    xmlcatalog --noout --add "rewriteSystem" \
      "http://www.oasis-open.org/docbook/xml/$DTDVERSION"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1" \
      %{install-root}/etc/xml/docbook


    xmlcatalog --noout --add "rewriteURI" \
      "http://www.oasis-open.org/docbook/xml/$DTDVERSION"  \
      "file:///usr/share/xml/docbook/xml-dtd-5.1" \
      %{install-root}/etc/xml/docbook

    xmlcatalog --noout --add "delegateSystem" \
      "http://www.oasis-open.org/docbook/xml/$DTDVERSION/"  \
      "file:///etc/xml/docbook" \
      %{install-root}/etc/xml/catalog


    xmlcatalog --noout --add "delegateURI" \
      "http://www.oasis-open.org/docbook/xml/$DTDVERSION/"  \
      "file:///etc/xml/docbook" \
      %{install-root}/etc/xml/catalog
  done

sources:
  - https://archive.docbook.org/xml/%{version}/docbook-xml-%{version}.zip

depends:
  - libxml2
