id: libxkbcommon
version: 1.13.2
about: Keymap compiler and support library which processes a reduced subset of keymaps as defined by the XKB specification
sources:
  - https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-%{version}.tar.gz

configure: >-
  --buildtype=release
  -Denable-docs=false

depends:
  - libxml2
  - xkeyboard-config
  - wayland-protocols
  - libxcb
