shell = /usr/bin/sh
hostname = avyos
services = dbgd uevent login distro http waylayer

[rescue]
enable = true
# tty = /dev/ttyS0

[environment]
PATH = /usr/bin:/usr/sbin
# AVYOS_GRAPHICS_TRACE_FRAMES = true
# AVYOS_GRAPHICS_TRACE_EVERY = 30

[network]
devices = lo eth0

[network.eth0]
ip = 10.0.2.15/24
route = 10.0.2.2

[restore]
files = /etc/init.conf /etc/init.d /etc/passwd /etc/group /etc/shadow /etc/uevent.conf
files = /etc/certificates/ca-certificates.crt
files = /etc/distro.ini /etc/fonts.ini
files = /etc/http.conf /etc/net.conf