id: mokutil
version: 0.7.2
about: Utility for managing Machine Owner Keys (MOK) on Linux

build-type: autotools

depends:
  - efivar
  - keyutils
  - libxcrypt
  - openssl

sources:
  - mokutil-%{version}.tar.gz::https://github.com/lcp/mokutil/archive/refs/tags/%{version}.tar.gz
