id: template-glib
version: 3.40.0
about: A templating library for GLib

depends:
  - glib
  - gobject-introspection
build-depends:
  - gtk-doc
  - meson
  - vala
sources:
  - https://download.gnome.org/sources/%{id}/%{version:2}/%{id}-%{version}.tar.xz
