id: inetutils
version: 2.8
about: Package contains programs for basic networking

pre-script: |-
  sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c

configure: >
  --disable-logger
  --disable-whois
  --disable-rcp
  --disable-rexec
  --disable-rlogin
  --disable-rsh
  --disable-servers

depends:
  - glibc
  - libcap
  - pam
  - ncurses

build-depends:
  - help2man
  - git

sources:
  - https://ftpmirror.gnu.org/inetutils/inetutils-%{version}.tar.gz
