id: iproute2
version: 7.0.0
about: IP Routing Utilities
sources:
  - https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-%{version}.tar.gz

pre-script: |-
  sed -i "s/-Werror//" Makefile
  sed -i /ARPD/d Makefile

script: |-
  make
  make SBINDIR=%{bindir} DESTDIR=%{install-root} install

depends:
  - glibc
  - iptables
  - libelf
  - libcap
build-depends:
  - flex
  - bison
