id = "dev.avyos.service"

types {
    ServiceNameRequest {
        fields {
            Name { type = string }
        }
    }
    ServiceStatus {
        fields {
            Description { type = string }
            Failed      { type = bool }
            Name        { type = string }
            PID         { type = int32 }
            Restart     { type = string }
            Running     { type = bool }
            Started     { type = bool }
            Type        { type = string }
        }
    }
    ServiceStatusList {
        fields {
            Items { type = "[]ServiceStatus" }
        }
    }
}

objects {
    Service {
        requests {
            GetStatus {
                in  = ["ServiceNameRequest"]
                out = ["ServiceStatus"]
            }
            ListServices {
                out = ["ServiceStatusList"]
            }
            RestartService {
                in = ["ServiceNameRequest"]
            }
            StartService {
                in = ["ServiceNameRequest"]
            }
            StopService {
                in = ["ServiceNameRequest"]
            }
            SystemPoweroff {
            }
            SystemReboot {
            }
        }
    }
}
