// Code generated by genapi from dev.avyos.service. DO NOT EDIT.
package service

import (
	"avyos.dev/lib/sutra"
	"net"
)

// Client holds connections to all objects in the dev.avyos.service service.
type Client struct {
	conn    *sutra.Conn
	Service *ServiceClient
}

// Connect dials the dev.avyos.service service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", "/run/dev.avyos.service.sock")
	if err != nil {
		return nil, err
	}
	conn := sutra.NewConn(nc)
	return &Client{
		conn:    conn,
		Service: NewServiceClient(conn, 0),
	}, nil
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type ServiceClient struct {
	Conn   *sutra.Conn
	Object uint32
}

func NewServiceClient(conn *sutra.Conn, object uint32) *ServiceClient {
	return &ServiceClient{Conn: conn, Object: object}
}

func (c *ServiceClient) GetStatus(in ServiceNameRequest) (ServiceStatus, error) {
	var zero ServiceStatus
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceGetStatus, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ServiceStatus](resp.Payload)
}

func (c *ServiceClient) ListServices() (ServiceStatusList, error) {
	var zero ServiceStatusList
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceListServices})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ServiceStatusList](resp.Payload)
}

func (c *ServiceClient) RestartService(in ServiceNameRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceRestartService, Payload: payload})
	return err
}

func (c *ServiceClient) StartService(in ServiceNameRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceStartService, Payload: payload})
	return err
}

func (c *ServiceClient) StopService(in ServiceNameRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceStopService, Payload: payload})
	return err
}

func (c *ServiceClient) SystemPoweroff() error {
	_, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceSystemPoweroff})
	return err
}

func (c *ServiceClient) SystemReboot() error {
	_, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpServiceSystemReboot})
	return err
}
