// Code generated by genapi from dev.avyos.service. DO NOT EDIT.
package service

import (
	"avyos.dev/lib/sutra"
	"fmt"
	"net"
)

type ServiceHandler interface {
	GetStatus(object uint32, in ServiceNameRequest) (ServiceStatus, error)
	ListServices(object uint32) (ServiceStatusList, error)
	RestartService(object uint32, in ServiceNameRequest) error
	StartService(object uint32, in ServiceNameRequest) error
	StopService(object uint32, in ServiceNameRequest) error
	SystemPoweroff(object uint32) error
	SystemReboot(object uint32) error
}

type Handlers struct {
	Service ServiceHandler
}

func Dispatch(h Handlers, conn *sutra.Conn, tx sutra.Transaction) error {
	switch tx.Event {
	case OpServiceGetStatus:
		in, err := sutra.UnmarshalPayload[ServiceNameRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Service.GetStatus: %w", err)
		}
		out, err := h.Service.GetStatus(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Service.GetStatus: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpServiceListServices:
		out, err := h.Service.ListServices(tx.Object)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Service.ListServices: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpServiceRestartService:
		in, err := sutra.UnmarshalPayload[ServiceNameRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Service.RestartService: %w", err)
		}
		if err := h.Service.RestartService(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpServiceStartService:
		in, err := sutra.UnmarshalPayload[ServiceNameRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Service.StartService: %w", err)
		}
		if err := h.Service.StartService(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpServiceStopService:
		in, err := sutra.UnmarshalPayload[ServiceNameRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Service.StopService: %w", err)
		}
		if err := h.Service.StopService(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpServiceSystemPoweroff:
		if err := h.Service.SystemPoweroff(tx.Object); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpServiceSystemReboot:
		if err := h.Service.SystemReboot(tx.Object); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	default:
		return fmt.Errorf("unknown opcode: %d", tx.Event)
	}
}

// Server listens on the dev.avyos.service Unix socket and dispatches incoming requests.
type Server struct {
	Handlers
	ln net.Listener
}

// Listen creates the dev.avyos.service Unix socket and returns a Server ready to serve.
func Listen() (*Server, error) {
	ln, err := net.Listen("unix", "/run/dev.avyos.service")
	if err != nil {
		return nil, err
	}
	return &Server{ln: ln}, nil
}

// Serve accepts connections and dispatches each transaction in a goroutine.
// It blocks until Close is called or a fatal accept error occurs.
func (s *Server) Serve() error {
	for {
		nc, err := s.ln.Accept()
		if err != nil {
			return err
		}
		go s.serveConn(nc)
	}
}

func (s *Server) serveConn(nc net.Conn) {
	conn := sutra.NewConn(nc)
	defer conn.Close()
	for {
		tx, err := conn.Recv()
		if err != nil {
			return
		}
		if err := Dispatch(s.Handlers, conn, tx); err != nil {
			return
		}
	}
}

// Close stops the listener.
func (s *Server) Close() error {
	return s.ln.Close()
}
