// Code generated by genapi from dev.avyos.service. DO NOT EDIT.
package service

type ServiceNameRequest struct {
	Name string
}

type ServiceStatus struct {
	Description string
	Failed      uint8
	Name        string
	PID         int32
	Restart     string
	Running     uint8
	Started     uint8
	Type        string
}

type ServiceStatusList struct {
	Items []ServiceStatus
}

const (
	OpServiceGetStatus      uint16 = 1
	OpServiceListServices   uint16 = 2
	OpServiceRestartService uint16 = 3
	OpServiceStartService   uint16 = 4
	OpServiceStopService    uint16 = 5
	OpServiceSystemPoweroff uint16 = 6
	OpServiceSystemReboot   uint16 = 7
)
