id: glade
version: 3.40.0
about: User Interface Builder for GTK+ applications

build-depends:
  - components/gtk3.yml
  - components/libxml2.yml
  - components/docbook-xsl.yml
  - components/gobject-introspection.yml
  - components/itstool.yml
  - components/meson.yml
  - components/python-gobject.yml
sources:
  - https://gitlab.gnome.org/GNOME/glade/-/archive/GLADE_3_40_0/glade-GLADE_3_40_0.tar.gz
