id: mesa-utils
version: 9.0.0
about: Essential Mesa utilities

configure: >-
  -D gles1=disabled
  -D osmesa=disabled

depends:
  - glew
  - mesa

sources:
  - https://mesa.freedesktop.org/archive/demos/mesa-demos-%{version}.tar.xz
