id: wireplumber
version: 0.5.14
about: A session and policy manager for Pipewire

configure: >-
  --buildtype=release
  -D system-lua=true
  
post-script: |-
    install -v -D -m 0644 /dev/stdin %{install-root}/%{libdir}/systemd/user-preset/%{id}.conf << "EOF"
    enable wireplumber.socket
    EOF

depends:
  - glib
  - systemd
  - pipewire
  - lua
  - gobject-introspection

sources:
  - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/%{version}/wireplumber-%{version}.tar.bz2