id: kross
merge: [external/kf5.inc]
about: KF5 kross

depends:
  - kparts
build-depends:
  - extra-cmake-modules
  - kdoctools

sources:
  - https://download.kde.org/stable/frameworks/%{version:2}/portingAids/%{id}-%{version}.tar.xz
