id: i3
version: 4.25.1
about: Improved dynamic tiling window manager

depends:
  - libev
  - pango
  - libxkbcommon
  - startup-notification
  - xcb-util-cursor
  - xcb-util-keysyms
  - xcb-util-wm
  - xcb-util-xrm
  - yajl

build-depends:
  - meson

sources:
  - https://i3wm.org/downloads/i3-%{version}.tar.xz