id: spirv-llvm-translator
version: 22.1.2
about: SPIR-V llvm translator

configure: >-
  -DCMAKE_SKIP_INSTALL_RPATH=ON
  -DBUILD_SHARED_LIBS=ON
  -DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=%{prefix}

depends:
  - libxml2

build-depends:
  - llvm
  - spirv-tools

sources:
  - https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v%{version}/SPIRV-LLVM-Translator-%{version}.tar.gz
