.TOPDIR ?= ..
include ${.TOPDIR}/build/avyos.defaults.inc

SUBDIR := expat ffi udev xml pixman zlib
SUBDIR += seat wayland wayland-protocols
SUBDIR += display-info hwdata mtdev evdev input
SUBDIR += pciaccess drm mesa xkbcommon wlroots

include ${.TOPDIR}/build/avyos.subdir.inc