.TOPDIR ?= ..
include ${.TOPDIR}/build/avyos.defaults.inc

SUBDIR := expat ffi udev xml pixman zlib
SUBDIR += seat wayland wayland-protocols
SUBDIR += display-info hwdata mtdev evdev input
SUBDIR += pciaccess drm mesa xkbcommon wlroots
SUBDIR += glfw tllist
SUBDIR += freetype fontconfig fcft

include ${.TOPDIR}/build/avyos.subdir.inc