id: terminology
version: 1.14.0
about: EFL based terminal emulator

depends:
  - efl

build-depends:
  - meson

sources:
  - https://download.enlightenment.org/rel/apps/terminology/terminology-%{version}.tar.xz
