id: zsh-syntax-highlighting
version: 0.8.0

depends:
  - glibc

script: |-
  mkdir -p %{install-root}%{datadir}/ohmyzsh/custom/plugins/%{id}
  cp -r *  %{install-root}%{datadir}/ohmyzsh/custom/plugins/%{id}/
  cp -r .revision-hash .version %{install-root}%{datadir}/ohmyzsh/custom/plugins/%{id}/

sources:
  - zsh-syntax-highlighting-%{version}.tar.gz::https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/%{version}.tar.gz
