id = "dev.avyos.uevent"

types {
    DeviceEvent {
        fields {
            Action    { type = string }
            DevName   { type = string }
            DevPath   { type = string }
            DevType   { type = string }
            Major     { type = int32 }
            Minor     { type = int32 }
            Subsystem { type = string }
        }
    }
    DeviceInfo {
        fields {
            DevName   { type = string }
            DevPath   { type = string }
            DevType   { type = string }
            Driver    { type = string }
            Major     { type = int32 }
            Minor     { type = int32 }
            Subsystem { type = string }
        }
    }
    DeviceList {
        fields {
            Devices { type = "[]DeviceInfo" }
        }
    }
    TriggerRequest {
        fields {
            Subsystem { type = string }
        }
    }
}

objects {
    Uevent {
        requests {
            GetDevice {
                in  = ["DeviceInfo"]
                out = ["DeviceInfo"]
            }
            ListDevices {
                out = ["DeviceList"]
            }
            Trigger {
                in = ["TriggerRequest"]
            }
        }
        events {
            DeviceAdded {
                args = ["DeviceEvent"]
            }
            DeviceChanged {
                args = ["DeviceEvent"]
            }
            DeviceRemoved {
                args = ["DeviceEvent"]
            }
        }
    }
}
