// Code generated by genapi from dev.avyos.uevent. DO NOT EDIT.
package uevent

import (
	"avyos.dev/lib/sutra"
	"net"
	"sync"
)

// Client holds connections to all objects in the dev.avyos.uevent service.
type Client struct {
	conn   *sutra.Conn
	Uevent *UeventClient
}

// Connect dials the dev.avyos.uevent service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", "/run/dev.avyos.uevent")
	if err != nil {
		return nil, err
	}
	return newClient(sutra.NewConn(nc)), nil
}

func newClient(conn *sutra.Conn) *Client {
	cl := &Client{
		conn:   conn,
		Uevent: NewUeventClient(conn, 0),
	}
	go cl.receiveLoop()
	return cl
}

func (cl *Client) receiveLoop() {
	for {
		tx, err := cl.conn.Recv()
		if err != nil {
			return
		}
		if !cl.conn.Route(tx) {
			_ = cl.HandleEvent(tx)
		}
	}
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Uevent)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type UeventClient struct {
	Conn          *sutra.Conn
	Object        uint32
	callbackMu    sync.RWMutex
	deviceAdded   func(args DeviceEvent)
	deviceChanged func(args DeviceEvent)
	deviceRemoved func(args DeviceEvent)
}

func NewUeventClient(conn *sutra.Conn, object uint32) *UeventClient {
	return &UeventClient{Conn: conn, Object: object}
}

func (c *UeventClient) OnDeviceAdded(fn func(args DeviceEvent)) {
	c.callbackMu.Lock()
	c.deviceAdded = fn
	c.callbackMu.Unlock()
}

func (c *UeventClient) OnDeviceChanged(fn func(args DeviceEvent)) {
	c.callbackMu.Lock()
	c.deviceChanged = fn
	c.callbackMu.Unlock()
}

func (c *UeventClient) OnDeviceRemoved(fn func(args DeviceEvent)) {
	c.callbackMu.Lock()
	c.deviceRemoved = fn
	c.callbackMu.Unlock()
}

func (c *UeventClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpUeventDeviceAdded:
		c.callbackMu.RLock()
		fn := c.deviceAdded
		c.callbackMu.RUnlock()
		if fn != nil {
			args, err := sutra.UnmarshalPayload[DeviceEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			fn(args)
		}
		return true, nil
	case OpUeventDeviceChanged:
		c.callbackMu.RLock()
		fn := c.deviceChanged
		c.callbackMu.RUnlock()
		if fn != nil {
			args, err := sutra.UnmarshalPayload[DeviceEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			fn(args)
		}
		return true, nil
	case OpUeventDeviceRemoved:
		c.callbackMu.RLock()
		fn := c.deviceRemoved
		c.callbackMu.RUnlock()
		if fn != nil {
			args, err := sutra.UnmarshalPayload[DeviceEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			fn(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *UeventClient) GetDevice(in DeviceInfo) (DeviceInfo, error) {
	var zero DeviceInfo
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpUeventGetDevice, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[DeviceInfo](resp.Payload)
}

func (c *UeventClient) ListDevices() (DeviceList, error) {
	var zero DeviceList
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpUeventListDevices})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[DeviceList](resp.Payload)
}

func (c *UeventClient) Trigger(in TriggerRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpUeventTrigger, Payload: payload})
	return err
}
