// Code generated by genapi from dev.avyos.uevent. DO NOT EDIT.
package uevent

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"net"
)

// Client holds connections to all objects in the dev.avyos.uevent service.
type Client struct {
	conn   *sutra.Conn
	Uevent *UeventClient
}

// Connect dials the dev.avyos.uevent service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", fs.Resolve("service:dev.avyos.uevent"))
	if err != nil {
		return nil, err
	}
	conn := sutra.NewConn(nc)
	return &Client{
		conn:   conn,
		Uevent: NewUeventClient(conn, 0),
	}, nil
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Uevent)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type UeventClient struct {
	Conn          *sutra.Conn
	Object        uint32
	deviceAdded   func(args DeviceEvent)
	deviceChanged func(args DeviceEvent)
	deviceRemoved func(args DeviceEvent)
}

func NewUeventClient(conn *sutra.Conn, object uint32) *UeventClient {
	return &UeventClient{Conn: conn, Object: object}
}

func (c *UeventClient) OnDeviceAdded(fn func(args DeviceEvent)) {
	c.deviceAdded = fn
}

func (c *UeventClient) OnDeviceChanged(fn func(args DeviceEvent)) {
	c.deviceChanged = fn
}

func (c *UeventClient) OnDeviceRemoved(fn func(args DeviceEvent)) {
	c.deviceRemoved = fn
}

func (c *UeventClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpUeventDeviceAdded:
		if c.deviceAdded != nil {
			args, err := sutra.UnmarshalPayload[DeviceEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.deviceAdded(args)
		}
		return true, nil
	case OpUeventDeviceChanged:
		if c.deviceChanged != nil {
			args, err := sutra.UnmarshalPayload[DeviceEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.deviceChanged(args)
		}
		return true, nil
	case OpUeventDeviceRemoved:
		if c.deviceRemoved != nil {
			args, err := sutra.UnmarshalPayload[DeviceEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.deviceRemoved(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *UeventClient) GetDevice(in DeviceInfo) (DeviceInfo, error) {
	var zero DeviceInfo
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpUeventGetDevice, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[DeviceInfo](resp.Payload)
}

func (c *UeventClient) ListDevices() (DeviceList, error) {
	var zero DeviceList
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpUeventListDevices})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[DeviceList](resp.Payload)
}

func (c *UeventClient) Trigger(in TriggerRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpUeventTrigger, Payload: payload})
	return err
}
