// Code generated by genapi from dev.avyos.uevent. DO NOT EDIT.
package uevent

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"fmt"
	"net"
)

type UeventHandler interface {
	GetDevice(object uint32, in DeviceInfo) (DeviceInfo, error)
	ListDevices(object uint32) (DeviceList, error)
	Trigger(object uint32, in TriggerRequest) error
}

type Handlers struct {
	Uevent UeventHandler
}

func Dispatch(h Handlers, conn *sutra.Conn, tx sutra.Transaction) error {
	switch tx.Event {
	case OpUeventGetDevice:
		in, err := sutra.UnmarshalPayload[DeviceInfo](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Uevent.GetDevice: %w", err)
		}
		out, err := h.Uevent.GetDevice(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Uevent.GetDevice: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpUeventListDevices:
		out, err := h.Uevent.ListDevices(tx.Object)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Uevent.ListDevices: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpUeventTrigger:
		in, err := sutra.UnmarshalPayload[TriggerRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Uevent.Trigger: %w", err)
		}
		if err := h.Uevent.Trigger(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	default:
		return fmt.Errorf("unknown opcode: %d", tx.Event)
	}
}

func SendUeventDeviceAdded(conn *sutra.Conn, object uint32, args DeviceEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpUeventDeviceAdded, Payload: payload})
}

func SendUeventDeviceChanged(conn *sutra.Conn, object uint32, args DeviceEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpUeventDeviceChanged, Payload: payload})
}

func SendUeventDeviceRemoved(conn *sutra.Conn, object uint32, args DeviceEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpUeventDeviceRemoved, Payload: payload})
}

// Server listens on the dev.avyos.uevent Unix socket and dispatches incoming requests.
type Server struct {
	Handlers
	ln net.Listener
}

// Listen creates the dev.avyos.uevent Unix socket and returns a Server ready to serve.
func Listen() (*Server, error) {
	ln, err := net.Listen("unix", fs.Resolve("service:dev.avyos.uevent"))
	if err != nil {
		return nil, err
	}
	return &Server{ln: ln}, nil
}

// Serve accepts connections and dispatches each transaction in a goroutine.
// It blocks until Close is called or a fatal accept error occurs.
func (s *Server) Serve() error {
	for {
		nc, err := s.ln.Accept()
		if err != nil {
			return err
		}
		go s.serveConn(nc)
	}
}

func (s *Server) serveConn(nc net.Conn) {
	conn := sutra.NewConn(nc)
	defer conn.Close()
	for {
		tx, err := conn.Recv()
		if err != nil {
			return
		}
		if err := Dispatch(s.Handlers, conn, tx); err != nil {
			return
		}
	}
}

// Close stops the listener.
func (s *Server) Close() error {
	return s.ln.Close()
}
