// Code generated by genapi from dev.avyos.uevent. DO NOT EDIT.
package uevent

type DeviceEvent struct {
	Action    string
	DevName   string
	DevPath   string
	DevType   string
	Major     int32
	Minor     int32
	Subsystem string
}

type DeviceInfo struct {
	DevName   string
	DevPath   string
	DevType   string
	Driver    string
	Major     int32
	Minor     int32
	Subsystem string
}

type DeviceList struct {
	Devices []DeviceInfo
}

type TriggerRequest struct {
	Subsystem string
}

const (
	OpUeventGetDevice     uint16 = 1
	OpUeventListDevices   uint16 = 2
	OpUeventTrigger       uint16 = 3
	OpUeventDeviceAdded   uint16 = 4
	OpUeventDeviceChanged uint16 = 5
	OpUeventDeviceRemoved uint16 = 6
)
