id: bubblewrap
version: 0.11.2
about: A setuid implementation of user namespaces, or sandboxing, that provides access to a subset of kernel user namespace features

depends:
  - glibc

sources:
  - https://github.com/projectatomic/bubblewrap/releases/download/v%{version}/bubblewrap-%{version}.tar.xz
