shell = /avyos/cmd/shell
hostname = avyos
services = dbg uevent login distro http

[rescue]
enable = true
# tty = device:ttyS0

[environment]
PATH = /avyos/cmd
# AVYOS_GRAPHICS_TRACE_FRAMES = true
# AVYOS_GRAPHICS_TRACE_EVERY = 30

[network]
devices = lo eth0

[network.eth0]
ip = 10.0.2.15/24
route = 10.0.2.2
