id: fontconfig
version: 2.17.1
about: Library and support programs used for configuring and customizing font access

build-type: autotools
configure: >-
  --sysconfdir=%{sysconfdir}

integration: |-
  fc-cache -s

sources:
  - https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/%{version}/fontconfig-%{version}.tar.gz
depends:
  - components/freetype.yml

build-depends:
  - components/gperf.yml
