id: libconfig
version: 1.8.2
about: C/C++ configuration file library

build-type: autotools

pre-script: autoreconf -fiv

build-depends:
  - components/texinfo.yml

sources:
  - libconfig-%{version}.tar.gz::https://github.com/hyperrealm/libconfig/archive/v%{version}.tar.gz
