id: libsigc++
version: 3.8.0
about: A typesafe callback system for standard C++

variables:
  run-autogen: false

sources:
  - https://github.com/libsigcplusplus/libsigcplusplus/releases/download/%{version}/libsigc++-%{version}.tar.xz

depends:
  - glibc
