id: thermald
version: 2.5.11
about: Linux Thermal Daemon program

build-type: autotools
environ:
  - NOCONFIGURE=1

configure: >-
  --with-dbus-sys-dir=%{datadir}/dbus-1/system.d

depends:
  - dbus-glib
  - libxml2
  - libevdev
  - upower
build-depends:
  - gtk-doc
sources:
  - https://github.com/intel/thermal_daemon/archive/v%{version}/thermald-%{version}.tar.gz
