id: kjsembed
merge: [external/kf5.inc]
about: KF5 kjsembed

depends:
  - ki18n
  - kjs
build-depends:
  - extra-cmake-modules
  - kdoctools

sources:
  - https://download.kde.org/stable/frameworks/%{version:2}/portingAids/%{id}-%{version}.tar.xz
