id: update-config
version: 0.0.3
merge: [channel.yml]
about: systemd-repart and systemd-sysupdate configuration

build-depends:
  - components/systemd.yml

script: |-
  update_url="https://repo.avyos.dev/updates/%{channel}/"

  install -d \
    "%{install-root}/%{libdir}/repart.d" \
    "%{install-root}/%{libdir}/sysupdate.d" \
    "%{install-root}/%{libdir}/systemd/system/sysinit.target.wants"

  for file in 10-efi.conf 20-usr-A.conf 21-usr-verity-A.conf 30-usr-B.conf 31-usr-verity-B.conf 90-root.conf; do
    install -m 0644 "%{build-root}/${file}" "%{install-root}/%{libdir}/repart.d/${file}"
  done

  for file in avyos-kernel.conf avyos-usr-verity.conf avyos-usr.conf; do
    target="${file%.conf}.transfer"
    sed "s#@UPDATE_URL@#${update_url}#g" "%{build-root}/${file}" \
      >"%{install-root}/%{libdir}/sysupdate.d/${target}"
    chmod 0644 "%{install-root}/%{libdir}/sysupdate.d/${target}"
  done

  ln -sf ../systemd-sysext.service \
    "%{install-root}/%{libdir}/systemd/system/sysinit.target.wants/systemd-sysext.service"

sources:
  - files/core/systemd-repart-config/10-efi.conf
  - files/core/systemd-repart-config/20-usr-A.conf
  - files/core/systemd-repart-config/21-usr-verity-A.conf
  - files/core/systemd-repart-config/30-usr-B.conf
  - files/core/systemd-repart-config/31-usr-verity-B.conf
  - files/core/systemd-repart-config/90-root.conf
  - files/core/systemd-sysupdate-config/avyos-kernel.conf
  - files/core/systemd-sysupdate-config/avyos-usr-verity.conf
  - files/core/systemd-sysupdate-config/avyos-usr.conf
