#Type    Path        Mode    User    Group   Age     Args
L        /bin        -       -       -       -       /usr/bin
L        /sbin       -       -       -       -       /usr/sbin
L        /lib        -       -       -       -       /usr/lib
