C /etc/init.d
C /etc/security
C /etc/certificates
C /etc/http
C /etc/fstab
C /etc/group
C /etc/hostname
C /etc/hosts
C /etc/http.conf
C /etc/init.conf
C /etc/net.conf
C /etc/passwd
C /etc/profile
C /etc/resolv.conf
C /etc/shadow
C /etc/shells
C /etc/uevent.conf
