id: libxfce4windowing
version: 4.20.5
about: Windowing concept abstraction library for X11 and Wayland

configure: >-
  --enable-x11
  --disable-debug

depends:
  - gtk3
  - libdisplay-info
  - libwnck

build-depends:
  - xfce4-dev-tools

sources:
  - https://archive.xfce.org/src/xfce/libxfce4windowing/%{version:2}/libxfce4windowing-%{version}.tar.bz2
