// Code generated by genapi from dev.avyos.desktop. DO NOT EDIT.
package desktop

import (
	"avyos.dev/lib/sutra"
	"net"
)

// Client holds connections to all objects in the dev.avyos.desktop service.
type Client struct {
	conn    *sutra.Conn
	Desktop *DesktopClient
}

// Connect dials the dev.avyos.desktop service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", "/run/dev.avyos.desktop.sock")
	if err != nil {
		return nil, err
	}
	conn := sutra.NewConn(nc)
	return &Client{
		conn:    conn,
		Desktop: NewDesktopClient(conn, 0),
	}, nil
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Desktop)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type DesktopClient struct {
	Conn           *sutra.Conn
	Object         uint32
	closeRequested func(args WindowRequest)
	input          func(args WindowInputEvent)
	resize         func(args WindowResizeEvent)
}

func NewDesktopClient(conn *sutra.Conn, object uint32) *DesktopClient {
	return &DesktopClient{Conn: conn, Object: object}
}

func (c *DesktopClient) OnCloseRequested(fn func(args WindowRequest)) {
	c.closeRequested = fn
}

func (c *DesktopClient) OnInput(fn func(args WindowInputEvent)) {
	c.input = fn
}

func (c *DesktopClient) OnResize(fn func(args WindowResizeEvent)) {
	c.resize = fn
}

func (c *DesktopClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpDesktopCloseRequested:
		if c.closeRequested != nil {
			args, err := sutra.UnmarshalPayload[WindowRequest](tx.Payload)
			if err != nil {
				return true, err
			}
			c.closeRequested(args)
		}
		return true, nil
	case OpDesktopInput:
		if c.input != nil {
			args, err := sutra.UnmarshalPayload[WindowInputEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.input(args)
		}
		return true, nil
	case OpDesktopResize:
		if c.resize != nil {
			args, err := sutra.UnmarshalPayload[WindowResizeEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.resize(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *DesktopClient) CreateWindow(in WindowCreateRequest) (WindowCreateResponse, error) {
	var zero WindowCreateResponse
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopCreateWindow, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[WindowCreateResponse](resp.Payload)
}

func (c *DesktopClient) DestroyWindow(in WindowRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopDestroyWindow, Payload: payload})
	return err
}

func (c *DesktopClient) PresentWindow(in WindowPresentRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopPresentWindow, Payload: payload})
	return err
}

func (c *DesktopClient) SendNotification(in NotificationRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopSendNotification, Payload: payload})
	return err
}

func (c *DesktopClient) UpdateCursor(in WindowCursorRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopUpdateCursor, Payload: payload})
	return err
}

func (c *DesktopClient) UpdateWindowBuffer(in WindowBufferRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopUpdateWindowBuffer, Payload: payload})
	return err
}

func (c *DesktopClient) UpdateWindowState(in WindowStateRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDesktopUpdateWindowState, Payload: payload})
	return err
}
