// Code generated by genapi from dev.avyos.desktop. DO NOT EDIT.
package desktop

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"fmt"
	"net"
)

type DesktopHandler interface {
	CreateWindow(object uint32, in WindowCreateRequest) (WindowCreateResponse, error)
	DestroyWindow(object uint32, in WindowRequest) error
	PresentWindow(object uint32, in WindowPresentRequest) error
	SendNotification(object uint32, in NotificationRequest) error
	UpdateCursor(object uint32, in WindowCursorRequest) error
	UpdateWindowBuffer(object uint32, in WindowBufferRequest) error
	UpdateWindowState(object uint32, in WindowStateRequest) error
}

type Handlers struct {
	Desktop DesktopHandler
}

func Dispatch(h Handlers, conn *sutra.Conn, tx sutra.Transaction) error {
	switch tx.Event {
	case OpDesktopCreateWindow:
		in, err := sutra.UnmarshalPayload[WindowCreateRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.CreateWindow: %w", err)
		}
		out, err := h.Desktop.CreateWindow(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Desktop.CreateWindow: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDesktopDestroyWindow:
		in, err := sutra.UnmarshalPayload[WindowRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.DestroyWindow: %w", err)
		}
		if err := h.Desktop.DestroyWindow(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDesktopPresentWindow:
		in, err := sutra.UnmarshalPayload[WindowPresentRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.PresentWindow: %w", err)
		}
		if err := h.Desktop.PresentWindow(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDesktopSendNotification:
		in, err := sutra.UnmarshalPayload[NotificationRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.SendNotification: %w", err)
		}
		if err := h.Desktop.SendNotification(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDesktopUpdateCursor:
		in, err := sutra.UnmarshalPayload[WindowCursorRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.UpdateCursor: %w", err)
		}
		if err := h.Desktop.UpdateCursor(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDesktopUpdateWindowBuffer:
		in, err := sutra.UnmarshalPayload[WindowBufferRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.UpdateWindowBuffer: %w", err)
		}
		if err := h.Desktop.UpdateWindowBuffer(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDesktopUpdateWindowState:
		in, err := sutra.UnmarshalPayload[WindowStateRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Desktop.UpdateWindowState: %w", err)
		}
		if err := h.Desktop.UpdateWindowState(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	default:
		return fmt.Errorf("unknown opcode: %d", tx.Event)
	}
}

func SendDesktopCloseRequested(conn *sutra.Conn, object uint32, args WindowRequest) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDesktopCloseRequested, Payload: payload})
}

func SendDesktopInput(conn *sutra.Conn, object uint32, args WindowInputEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDesktopInput, Payload: payload})
}

func SendDesktopResize(conn *sutra.Conn, object uint32, args WindowResizeEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDesktopResize, Payload: payload})
}

// Server listens on the dev.avyos.desktop Unix socket and dispatches incoming requests.
type Server struct {
	Handlers
	ln net.Listener
}

// Listen creates the dev.avyos.desktop Unix socket and returns a Server ready to serve.
func Listen() (*Server, error) {
	ln, err := net.Listen("unix", fs.Resolve("service:dev.avyos.desktop"))
	if err != nil {
		return nil, err
	}
	return &Server{ln: ln}, nil
}

// Serve accepts connections and dispatches each transaction in a goroutine.
// It blocks until Close is called or a fatal accept error occurs.
func (s *Server) Serve() error {
	for {
		nc, err := s.ln.Accept()
		if err != nil {
			return err
		}
		go s.serveConn(nc)
	}
}

func (s *Server) serveConn(nc net.Conn) {
	conn := sutra.NewConn(nc)
	defer conn.Close()
	for {
		tx, err := conn.Recv()
		if err != nil {
			return
		}
		if err := Dispatch(s.Handlers, conn, tx); err != nil {
			return
		}
	}
}

// Close stops the listener.
func (s *Server) Close() error {
	return s.ln.Close()
}
