// Code generated by genapi from dev.avyos.desktop. DO NOT EDIT.
package desktop

type DamageRect struct {
	H uint32
	W uint32
	X uint32
	Y uint32
}

type NotificationRequest struct {
	AppId   string
	AppName string
	Icon    string
	Message string
	Title   string
}

type WindowBufferRequest struct {
	BufferPath string
	Height     uint32
	ScaleMilli uint32
	Width      uint32
	WindowId   uint32
}

type WindowCreateRequest struct {
	Accent     uint32
	AppId      string
	AppName    string
	BufferPath string
	Height     uint32
	Icon       string
	MinHeight  uint32
	MinWidth   uint32
	ScaleMilli uint32
	Status     string
	Subtitle   string
	Title      string
	Width      uint32
}

type WindowCreateResponse struct {
	WindowId uint32
}

type WindowCursorRequest struct {
	Shape    uint32
	WindowId uint32
}

type WindowInputEvent struct {
	Payload  []byte
	WindowId uint32
}

type WindowPresentRequest struct {
	BufferPath  string
	DamageRects []DamageRect
	WindowId    uint32
}

type WindowRequest struct {
	WindowId uint32
}

type WindowResizeEvent struct {
	Height   uint32
	Width    uint32
	WindowId uint32
}

type WindowStateRequest struct {
	Status   string
	Subtitle string
	Title    string
	WindowId uint32
}

const (
	OpDesktopCreateWindow       uint16 = 1
	OpDesktopDestroyWindow      uint16 = 2
	OpDesktopPresentWindow      uint16 = 3
	OpDesktopSendNotification   uint16 = 4
	OpDesktopUpdateCursor       uint16 = 5
	OpDesktopUpdateWindowBuffer uint16 = 6
	OpDesktopUpdateWindowState  uint16 = 7
	OpDesktopCloseRequested     uint16 = 8
	OpDesktopInput              uint16 = 9
	OpDesktopResize             uint16 = 10
)
