id: xfce4-smartbookmark-plugin
version: 0.6.0
about: Allows you to send requests directly to your browser and perform a custom search

build-depends:
  - libxt

merge: [external/xfce4-panel-plugin.inc]
