id: libisoburn
version: 1.5.8
about: A frontend for libraries libburn and libisofs

configure: >-
  --disable-static 
  --enable-pkg-check-modules 
  CFLAGS=" -I/usr/include -L/usr/lib"

sources:
  - https://files.libburnia-project.org/releases/libisoburn-%{version}.tar.gz
depends:
  - libburn
  - libisofs
