id: xdg-desktop-portal-gnome
version: 50.0
about: A backend implementation for xdg-desktop-portal for GNOME desktop environment

depends:
  - gnome-keyring
  - gtk4
  - xdg-desktop-portal-gtk
build-depends:
  - meson
  - xdg-desktop-portal
sources:
  - https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/archive/%{version}/xdg-desktop-portal-gnome-%{version}.tar.gz
