id: docbook-xml-5.0
version: 5.0
about: Package contains document type definitions for verification of XML data files against the DocBook rule set

script: |
  install -v -d -m 755 %{install-root}/usr/share/xml/docbook/xml-%{version}
  cp -rv catalog.xml dtd rng sch xsd %{install-root}/usr/share/xml/docbook/xml-%{version}

  install -v -d -m 755 %{install-root}/etc/xml
  xmlcatalog --noout --create %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegatePublic"             \
    "-//OASIS//DTD DocBook XML 5.0//EN                " \
    "file:///usr/share/xml/docbook/xml-%{version}/catalog.xml" \
    %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegateSystem"             \
    "http://docbook.org/xml/5.0/dtd/"                   \
    "file:///usr/share/xml/docbook/xml-%{version}/catalog.xml" \
    %{install-root}/etc/xml/catalog

  xmlcatalog --noout --add "delegateURI"                \
    "http://docbook.org/xml/5.0"                        \
    "file:///usr/share/xml/docbook/xml-%{version}/catalog.xml" \
    %{install-root}/etc/xml/catalog

sources:
  - https://archive.docbook.org/xml/%{version}/docbook-%{version}.zip

depends:
  - libxml2
