id = "dev.avyos.distro"

types {
    InstallRequest {
        fields {
            URL { type = string }
        }
    }
    RunRequest {
        fields {
            Bind    { type = string }
            Command { type = string }
            Env     { type = string }
            Input   { type = "[]byte" }
            Workdir { type = string }
        }
    }
    RunResult {
        fields {
            ExitCode { type = int32 }
            Stderr   { type = "[]byte" }
            Stdout   { type = "[]byte" }
        }
    }
    ShellCloseRequest {
        fields {
            SessionID { type = uint32 }
        }
    }
    ShellExitEvent {
        fields {
            ExitCode  { type = int32 }
            SessionID { type = uint32 }
        }
    }
    ShellInputRequest {
        fields {
            Data      { type = "[]byte" }
            SessionID { type = uint32 }
        }
    }
    ShellOpenRequest {
        fields {
            Bind    { type = string }
            Cols    { type = int32 }
            Env     { type = string }
            Rows    { type = int32 }
            Workdir { type = string }
        }
    }
    ShellOutputEvent {
        fields {
            Data      { type = "[]byte" }
            SessionID { type = uint32 }
        }
    }
    ShellResizeRequest {
        fields {
            Cols      { type = int32 }
            Rows      { type = int32 }
            SessionID { type = uint32 }
        }
    }
    ShellSession {
        fields {
            SessionID { type = uint32 }
        }
    }
    StatusResponse {
        fields {
            Installed { type = bool }
            Path      { type = string }
            Size      { type = int64 }
        }
    }
}

objects {
    Distro {
        requests {
            Install {
                in = ["InstallRequest"]
            }
            Remove {
            }
            Run {
                in  = ["RunRequest"]
                out = ["RunResult"]
            }
            ShellClose {
                in = ["ShellCloseRequest"]
            }
            ShellInput {
                in = ["ShellInputRequest"]
            }
            ShellOpen {
                in  = ["ShellOpenRequest"]
                out = ["ShellSession"]
            }
            ShellResize {
                in = ["ShellResizeRequest"]
            }
            Status {
                out = ["StatusResponse"]
            }
        }
        events {
            ShellExit {
                args = ["ShellExitEvent"]
            }
            ShellOutput {
                args = ["ShellOutputEvent"]
            }
        }
    }
}
