// Code generated by genapi from dev.avyos.distro. DO NOT EDIT.
package distro

import (
	"avyos.dev/lib/sutra"
	"net"
	"sync"
)

// Client holds connections to all objects in the dev.avyos.distro service.
type Client struct {
	conn   *sutra.Conn
	Distro *DistroClient
}

// Connect dials the dev.avyos.distro service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", "/run/dev.avyos.distro")
	if err != nil {
		return nil, err
	}
	return newClient(sutra.NewConn(nc)), nil
}

func newClient(conn *sutra.Conn) *Client {
	cl := &Client{
		conn:   conn,
		Distro: NewDistroClient(conn, 0),
	}
	go cl.receiveLoop()
	return cl
}

func (cl *Client) receiveLoop() {
	for {
		tx, err := cl.conn.Recv()
		if err != nil {
			return
		}
		if !cl.conn.Route(tx) {
			_ = cl.HandleEvent(tx)
		}
	}
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Distro)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type DistroClient struct {
	Conn        *sutra.Conn
	Object      uint32
	callbackMu  sync.RWMutex
	shellExit   func(args ShellExitEvent)
	shellOutput func(args ShellOutputEvent)
}

func NewDistroClient(conn *sutra.Conn, object uint32) *DistroClient {
	return &DistroClient{Conn: conn, Object: object}
}

func (c *DistroClient) OnShellExit(fn func(args ShellExitEvent)) {
	c.callbackMu.Lock()
	c.shellExit = fn
	c.callbackMu.Unlock()
}

func (c *DistroClient) OnShellOutput(fn func(args ShellOutputEvent)) {
	c.callbackMu.Lock()
	c.shellOutput = fn
	c.callbackMu.Unlock()
}

func (c *DistroClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpDistroShellExit:
		c.callbackMu.RLock()
		fn := c.shellExit
		c.callbackMu.RUnlock()
		if fn != nil {
			args, err := sutra.UnmarshalPayload[ShellExitEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			fn(args)
		}
		return true, nil
	case OpDistroShellOutput:
		c.callbackMu.RLock()
		fn := c.shellOutput
		c.callbackMu.RUnlock()
		if fn != nil {
			args, err := sutra.UnmarshalPayload[ShellOutputEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			fn(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *DistroClient) Install(in InstallRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroInstall, Payload: payload})
	return err
}

func (c *DistroClient) Remove() error {
	_, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroRemove})
	return err
}

func (c *DistroClient) Run(in RunRequest) (RunResult, error) {
	var zero RunResult
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroRun, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[RunResult](resp.Payload)
}

func (c *DistroClient) ShellClose(in ShellCloseRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellClose, Payload: payload})
	return err
}

func (c *DistroClient) ShellInput(in ShellInputRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellInput, Payload: payload})
	return err
}

func (c *DistroClient) ShellOpen(in ShellOpenRequest) (ShellSession, error) {
	var zero ShellSession
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellOpen, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ShellSession](resp.Payload)
}

func (c *DistroClient) ShellResize(in ShellResizeRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellResize, Payload: payload})
	return err
}

func (c *DistroClient) Status() (StatusResponse, error) {
	var zero StatusResponse
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroStatus})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[StatusResponse](resp.Payload)
}
