// Code generated by genapi from dev.avyos.distro. DO NOT EDIT.
package distro

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"net"
)

// Client holds connections to all objects in the dev.avyos.distro service.
type Client struct {
	conn   *sutra.Conn
	Distro *DistroClient
}

// Connect dials the dev.avyos.distro service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", fs.Resolve("service:dev.avyos.distro"))
	if err != nil {
		return nil, err
	}
	conn := sutra.NewConn(nc)
	return &Client{
		conn:   conn,
		Distro: NewDistroClient(conn, 0),
	}, nil
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Distro)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type DistroClient struct {
	Conn        *sutra.Conn
	Object      uint32
	shellExit   func(args ShellExitEvent)
	shellOutput func(args ShellOutputEvent)
}

func NewDistroClient(conn *sutra.Conn, object uint32) *DistroClient {
	return &DistroClient{Conn: conn, Object: object}
}

func (c *DistroClient) OnShellExit(fn func(args ShellExitEvent)) {
	c.shellExit = fn
}

func (c *DistroClient) OnShellOutput(fn func(args ShellOutputEvent)) {
	c.shellOutput = fn
}

func (c *DistroClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpDistroShellExit:
		if c.shellExit != nil {
			args, err := sutra.UnmarshalPayload[ShellExitEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.shellExit(args)
		}
		return true, nil
	case OpDistroShellOutput:
		if c.shellOutput != nil {
			args, err := sutra.UnmarshalPayload[ShellOutputEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.shellOutput(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *DistroClient) Install(in InstallRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroInstall, Payload: payload})
	return err
}

func (c *DistroClient) Remove() error {
	_, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroRemove})
	return err
}

func (c *DistroClient) Run(in RunRequest) (RunResult, error) {
	var zero RunResult
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroRun, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[RunResult](resp.Payload)
}

func (c *DistroClient) ShellClose(in ShellCloseRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellClose, Payload: payload})
	return err
}

func (c *DistroClient) ShellInput(in ShellInputRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellInput, Payload: payload})
	return err
}

func (c *DistroClient) ShellOpen(in ShellOpenRequest) (ShellSession, error) {
	var zero ShellSession
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellOpen, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ShellSession](resp.Payload)
}

func (c *DistroClient) ShellResize(in ShellResizeRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroShellResize, Payload: payload})
	return err
}

func (c *DistroClient) Status() (StatusResponse, error) {
	var zero StatusResponse
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDistroStatus})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[StatusResponse](resp.Payload)
}
