// Code generated by genapi from dev.avyos.distro. DO NOT EDIT.
package distro

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"fmt"
	"net"
)

type DistroHandler interface {
	Install(object uint32, in InstallRequest) error
	Remove(object uint32) error
	Run(object uint32, in RunRequest) (RunResult, error)
	ShellClose(object uint32, in ShellCloseRequest) error
	ShellInput(object uint32, in ShellInputRequest) error
	ShellOpen(object uint32, in ShellOpenRequest) (ShellSession, error)
	ShellResize(object uint32, in ShellResizeRequest) error
	Status(object uint32) (StatusResponse, error)
}

type Handlers struct {
	Distro DistroHandler
}

func Dispatch(h Handlers, conn *sutra.Conn, tx sutra.Transaction) error {
	switch tx.Event {
	case OpDistroInstall:
		in, err := sutra.UnmarshalPayload[InstallRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Distro.Install: %w", err)
		}
		if err := h.Distro.Install(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDistroRemove:
		if err := h.Distro.Remove(tx.Object); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDistroRun:
		in, err := sutra.UnmarshalPayload[RunRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Distro.Run: %w", err)
		}
		out, err := h.Distro.Run(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Distro.Run: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDistroShellClose:
		in, err := sutra.UnmarshalPayload[ShellCloseRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Distro.ShellClose: %w", err)
		}
		if err := h.Distro.ShellClose(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDistroShellInput:
		in, err := sutra.UnmarshalPayload[ShellInputRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Distro.ShellInput: %w", err)
		}
		if err := h.Distro.ShellInput(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDistroShellOpen:
		in, err := sutra.UnmarshalPayload[ShellOpenRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Distro.ShellOpen: %w", err)
		}
		out, err := h.Distro.ShellOpen(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Distro.ShellOpen: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDistroShellResize:
		in, err := sutra.UnmarshalPayload[ShellResizeRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Distro.ShellResize: %w", err)
		}
		if err := h.Distro.ShellResize(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDistroStatus:
		out, err := h.Distro.Status(tx.Object)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Distro.Status: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	default:
		return fmt.Errorf("unknown opcode: %d", tx.Event)
	}
}

func SendDistroShellExit(conn *sutra.Conn, object uint32, args ShellExitEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDistroShellExit, Payload: payload})
}

func SendDistroShellOutput(conn *sutra.Conn, object uint32, args ShellOutputEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDistroShellOutput, Payload: payload})
}

// Server listens on the dev.avyos.distro Unix socket and dispatches incoming requests.
type Server struct {
	Handlers
	ln net.Listener
}

// Listen creates the dev.avyos.distro Unix socket and returns a Server ready to serve.
func Listen() (*Server, error) {
	ln, err := net.Listen("unix", fs.Resolve("service:dev.avyos.distro"))
	if err != nil {
		return nil, err
	}
	return &Server{ln: ln}, nil
}

// Serve accepts connections and dispatches each transaction in a goroutine.
// It blocks until Close is called or a fatal accept error occurs.
func (s *Server) Serve() error {
	for {
		nc, err := s.ln.Accept()
		if err != nil {
			return err
		}
		go s.serveConn(nc)
	}
}

func (s *Server) serveConn(nc net.Conn) {
	conn := sutra.NewConn(nc)
	defer conn.Close()
	for {
		tx, err := conn.Recv()
		if err != nil {
			return
		}
		if err := Dispatch(s.Handlers, conn, tx); err != nil {
			return
		}
	}
}

// Close stops the listener.
func (s *Server) Close() error {
	return s.ln.Close()
}
