// Code generated by genapi from dev.avyos.distro. DO NOT EDIT.
package distro

type InstallRequest struct {
	URL string
}

type RunRequest struct {
	Bind    string
	Command string
	Env     string
	Input   []byte
	Workdir string
}

type RunResult struct {
	ExitCode int32
	Stderr   []byte
	Stdout   []byte
}

type ShellCloseRequest struct {
	SessionID uint32
}

type ShellExitEvent struct {
	ExitCode  int32
	SessionID uint32
}

type ShellInputRequest struct {
	Data      []byte
	SessionID uint32
}

type ShellOpenRequest struct {
	Bind    string
	Cols    int32
	Env     string
	Rows    int32
	Workdir string
}

type ShellOutputEvent struct {
	Data      []byte
	SessionID uint32
}

type ShellResizeRequest struct {
	Cols      int32
	Rows      int32
	SessionID uint32
}

type ShellSession struct {
	SessionID uint32
}

type StatusResponse struct {
	Installed uint8
	Path      string
	Size      int64
}

const (
	OpDistroInstall     uint16 = 1
	OpDistroRemove      uint16 = 2
	OpDistroRun         uint16 = 3
	OpDistroShellClose  uint16 = 4
	OpDistroShellInput  uint16 = 5
	OpDistroShellOpen   uint16 = 6
	OpDistroShellResize uint16 = 7
	OpDistroStatus      uint16 = 8
	OpDistroShellExit   uint16 = 9
	OpDistroShellOutput uint16 = 10
)
