id: chromaprint
version: 1.6.0
about: Library for extracting fingerprints from any audio source

configure: >
  -DCMAKE_BUILD_TYPE='None'
  -DBUILD_TESTS=ON
  -DBUILD_TOOLS=ON
  -Wno-dev

depends:
  - libgcc
  - glibc
  - ffmpeg

build-depends:
  - cmake

sources:
  - https://github.com/acoustid/chromaprint/archive/v%{version}/chromaprint-%{version}.tar.gz
#  - https://github.com/acoustid/chromaprint/commit/aa67c95b.patch
