id = "dev.avyos.login"

types {
    SessionInfo {
        fields {
            Active   { type = bool }
            PID      { type = int32 }
            UID      { type = uint32 }
            Username { type = string }
        }
    }
}

objects {
    Login {
        requests {
            GetSession {
                out = ["SessionInfo"]
            }
            Lock {
            }
            Logout {
            }
        }
        events {
            SessionEnded {
            }
            SessionStarted {
                args = ["SessionInfo"]
            }
        }
    }
}
