// Code generated by genapi from dev.avyos.login. DO NOT EDIT.
package login

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"net"
)

// Client holds connections to all objects in the dev.avyos.login service.
type Client struct {
	conn  *sutra.Conn
	Login *LoginClient
}

// Connect dials the dev.avyos.login service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", fs.Resolve("service:dev.avyos.login"))
	if err != nil {
		return nil, err
	}
	conn := sutra.NewConn(nc)
	return &Client{
		conn:  conn,
		Login: NewLoginClient(conn, 0),
	}, nil
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Login)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type LoginClient struct {
	Conn           *sutra.Conn
	Object         uint32
	sessionEnded   func()
	sessionStarted func(args SessionInfo)
}

func NewLoginClient(conn *sutra.Conn, object uint32) *LoginClient {
	return &LoginClient{Conn: conn, Object: object}
}

func (c *LoginClient) OnSessionEnded(fn func()) {
	c.sessionEnded = fn
}

func (c *LoginClient) OnSessionStarted(fn func(args SessionInfo)) {
	c.sessionStarted = fn
}

func (c *LoginClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpLoginSessionEnded:
		if c.sessionEnded != nil {
			c.sessionEnded()
		}
		return true, nil
	case OpLoginSessionStarted:
		if c.sessionStarted != nil {
			args, err := sutra.UnmarshalPayload[SessionInfo](tx.Payload)
			if err != nil {
				return true, err
			}
			c.sessionStarted(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *LoginClient) GetSession() (SessionInfo, error) {
	var zero SessionInfo
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpLoginGetSession})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[SessionInfo](resp.Payload)
}

func (c *LoginClient) Lock() error {
	_, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpLoginLock})
	return err
}

func (c *LoginClient) Logout() error {
	_, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpLoginLogout})
	return err
}
