// Code generated by genapi from dev.avyos.login. DO NOT EDIT.
package login

import (
	"avyos.dev/lib/sutra"
	"fmt"
	"net"
)

type LoginHandler interface {
	GetSession(object uint32) (SessionInfo, error)
	Lock(object uint32) error
	Logout(object uint32) error
}

type Handlers struct {
	Login LoginHandler
}

func Dispatch(h Handlers, conn *sutra.Conn, tx sutra.Transaction) error {
	switch tx.Event {
	case OpLoginGetSession:
		out, err := h.Login.GetSession(tx.Object)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Login.GetSession: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpLoginLock:
		if err := h.Login.Lock(tx.Object); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpLoginLogout:
		if err := h.Login.Logout(tx.Object); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	default:
		return fmt.Errorf("unknown opcode: %d", tx.Event)
	}
}

func SendLoginSessionEnded(conn *sutra.Conn, object uint32) error {
	return conn.Send(sutra.Transaction{Object: object, Event: OpLoginSessionEnded})
}

func SendLoginSessionStarted(conn *sutra.Conn, object uint32, args SessionInfo) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpLoginSessionStarted, Payload: payload})
}

// Server listens on the dev.avyos.login Unix socket and dispatches incoming requests.
type Server struct {
	Handlers
	ln net.Listener
}

// Listen creates the dev.avyos.login Unix socket and returns a Server ready to serve.
func Listen() (*Server, error) {
	ln, err := net.Listen("unix", "/run/dev.avyos.login")
	if err != nil {
		return nil, err
	}
	return &Server{ln: ln}, nil
}

// Serve accepts connections and dispatches each transaction in a goroutine.
// It blocks until Close is called or a fatal accept error occurs.
func (s *Server) Serve() error {
	for {
		nc, err := s.ln.Accept()
		if err != nil {
			return err
		}
		go s.serveConn(nc)
	}
}

func (s *Server) serveConn(nc net.Conn) {
	conn := sutra.NewConn(nc)
	defer conn.Close()
	for {
		tx, err := conn.Recv()
		if err != nil {
			return
		}
		if err := Dispatch(s.Handlers, conn, tx); err != nil {
			return
		}
	}
}

// Close stops the listener.
func (s *Server) Close() error {
	return s.ln.Close()
}
