// Code generated by genapi from dev.avyos.login. DO NOT EDIT.
package login

type SessionInfo struct {
	Active   uint8
	PID      int32
	UID      uint32
	Username string
}

const (
	OpLoginGetSession     uint16 = 1
	OpLoginLock           uint16 = 2
	OpLoginLogout         uint16 = 3
	OpLoginSessionEnded   uint16 = 4
	OpLoginSessionStarted uint16 = 5
)
