id: gnome-terminal
version: 3.60.0
about: Package contains the terminal emulator for GNOME Desktop

pre-script: |-
  sed -i -r 's:"(/system):"/org/gnome\1:g' src/external.gschema.xml

configure: >-
  --buildtype=release
  -Dsearch_provider=true
  -Dnautilus_extension=true

depends:
  - dconf
  - gnome-shell
  - gsettings-desktop-schemas
  - itstool
  - nautilus
  - pcre2
  - vte
sources:
  - https://download.gnome.org/sources/gnome-terminal/%{version:2}/gnome-terminal-%{version}.tar.xz
