id: image
merge: [version.yml, channel.yml]
about: System Image

capabilities:
  - CAP_SYS_CHROOT

salt: 5ceca5e1f86ae62403b27e66c5160717f1bb88405a1d1d0853241c27f3764843
force-rebuild: false
include:
- external/platform

include-root: /sysroot

script: |-
  chroot %{include-root} /bin/bash -e << "EOT"
  for i in %{datadir}/pkgupd/manifest/*/integration ; do
    sh -e $i
  done

  rm -rf /install-root

  ln -sfv %{datadir}/zoneinfo/UTC %{sysconfdir}/

  # TODO: FIX external/pam integration
  chmod 4755 %{bindir}/unix_chkpwd

  echo -e "\nGTK_CSD=1" >> %{sysconfdir}/environment

  sed -i 's/enable systemd-homed.service//g' %{libdir}/systemd/system-preset/90-systemd.preset
  sed -i 's/enable systemd-homed-activate.service//g' %{libdir}/systemd/system-preset/90-systemd.preset
  EOT

  # We are using our own pam config
  rm -rf %{include-root}/usr/lib/pam.d/systemd-user %{include-root}/usr/lib/pam.d/other

  cp -rlTP %{include-root}/etc/pam.d %{include-root}/usr/lib/pam.d
  rm -rf %{include-root}/etc/pam.d

  rm -rf %{include-root}/%{datadir}/factory/%{sysconfdir}
  mkdir -p %{include-root}/%{datadir}/factory
  cp -aT %{include-root}/%{sysconfdir} %{include-root}/%{datadir}/factory/%{sysconfdir}
  install -v -D -m 0644 /dev/stdin %{include-root}/%{libdir}/tmpfiles.d/00-rlxos-etc.conf << "EOF"
  C /etc/ModemManager
  C /etc/NetworkManager
  C /etc/UPower
  C /etc/X11
  C /etc/alsa
  C /etc/anthy-conf
  C /etc/appstream.conf
  C /etc/audit
  C /etc/avahi
  C /etc/bash_completion.d
  C /etc/bashrc
  C /etc/bindresvport.blacklist
  C /etc/binfmt.d
  C /etc/cups
  C /etc/cupshelpers
  C /etc/dbus-1
  C /etc/dconf
  C /etc/debuginfod
  C /etc/default
  C /etc/dracut.conf.d
  C /etc/e2scrub.conf
  C /etc/environment
  C /etc/ethertypes
  C /etc/fish
  C /etc/flatpak
  C /etc/fonts
  C /etc/fstab
  C /etc/fuse.conf
  C /etc/fwupd
  C /etc/gamemode.ini
  C /etc/gdm
  C /etc/geoclue
  C /etc/grub.d
  C /etc/gss
  C /etc/gtk-3.0
  C /etc/hosts
  C /etc/init.d
  C /etc/iscsi
  C /etc/isns
  C /etc/kernel
  C /etc/ld.so.conf
  C /etc/libaudit.conf
  C /etc/libblockdev
  C /etc/libinput
  C /etc/libnl
  C /etc/libsmbios
  C /etc/lightdm
  C /etc/locale.conf
  C /etc/localtime
  C /etc/login.defs
  C /etc/logrotate.d
  C /etc/lvm
  C /etc/man_db.conf
  C /etc/mke2fs.conf
  C /etc/modules-load.d
  C /etc/moduli
  C /etc/netconfig
  C /etc/nscd.conf
  C /etc/openfortivpn
  C /etc/openldap
  C /etc/opensc.conf
  C /etc/pkcs11
  C /etc/pki
  C /etc/plymouth
  C /etc/polkit-1
  C /etc/profile
  C /etc/profile.d
  C /etc/protocols
  C /etc/pulse
  C /etc/rc_keymaps
  C /etc/rc_maps.cfg
  C /etc/rpc
  C /etc/rygel.conf
  C /etc/samba
  C /etc/sane.d
  C /etc/securetty
  C /etc/security
  C /etc/services
  C /etc/shells
  C /etc/skel
  C /etc/speech-dispatcher
  C /etc/ssh_config
  C /etc/sshd_config
  C /etc/ssl
  C /etc/subgid
  C /etc/subuid
  C /etc/sudo.conf
  C /etc/sudo_logsrvd.conf
  C /etc/sudoers
  C /etc/sudoers.d
  C /etc/sudoers.dist
  C /etc/sysctl.d
  C /etc/tpm2-tss
  C /etc/udev
  C /etc/udisks2
  C /etc/uresourced.conf
  C /etc/vdpau_wrapper.cfg
  C /etc/xattr.conf
  C /etc/xdg
  C /etc/xml
  C /etc/xtables.conf
  C /etc/zsh
  L /etc/os-release - - - - /usr/lib/os-release
  C! /etc/audit
  C! /etc/pam.d
  C! /etc/security
  C! /etc/subgid
  C! /etc/subuid
  C! /etc/systemd/coredump.conf
  C! /etc/systemd/homed.conf
  C! /etc/systemd/journal-upload.conf
  C! /etc/systemd/journald.conf
  C! /etc/systemd/logind.conf
  C! /etc/systemd/networkd.conf
  C! /etc/systemd/oomd.conf
  C! /etc/systemd/pstore.conf
  C! /etc/systemd/resolved.conf
  C! /etc/systemd/sleep.conf
  C! /etc/systemd/system.conf
  C! /etc/systemd/timesyncd.conf
  C! /etc/systemd/user.conf
  C! /etc/issue.net
  EOF

  install -Dm644 /dev/stdin %{include-root}/%{libdir}/os-release << "EOF"
  NAME=rlxos
  VERSION=%{version}
  ID=rlxos
  PRETTY_NAME="rlxos %{version} %{channel}"
  HOME_URL="https://rlxos.org"
  SUPPORT_URL="https://rlxos.org/support"
  BUG_REPORT_URL="https://rlxos.org/bug-report"
  IMAGE_VERSION=%{version}
  EOF

  mkdir -p %{install-root}
  mksquashfs %{include-root}/%{prefix} %{install-root}/usr_%{version}.squashfs

  veritysetup format --salt="%{salt}" %{install-root}/usr_%{version}.squashfs %{install-root}/usr_%{version}.verity | sed '/^Root hash:[[:space:]]*/{;s///;q;};d' > %{install-root}/usr-root-hash.txt

  usr_part_uuid="$(cat "%{install-root}/usr-root-hash.txt" | sed -E 's/^([0-9a-f]{8})([0-9a-f]{4})([0-9a-f]{4})([0-9a-f]{4})([0-9a-f]{12}).*/\1\2\3\4\5/')"
  mv "%{install-root}/usr_%{version}.squashfs" "%{install-root}/usr_%{version}_${usr_part_uuid}.squashfs"
  ln -s "usr_%{version}_${usr_part_uuid}.squashfs" '%{install-root}/usr.squashfs'

  usr_verity_part_uuid="$(cat "%{install-root}/usr-root-hash.txt" | sed -E 's/.*([0-9a-f]{8})([0-9a-f]{4})([0-9a-f]{4})([0-9a-f]{4})([0-9a-f]{12})$/\1\2\3\4\5/')"
  mv "%{install-root}/usr_%{version}.verity" "%{install-root}/usr_%{version}_${usr_verity_part_uuid}.verity"
  chmod 0644 "%{install-root}/usr_%{version}_${usr_verity_part_uuid}.verity"
  ln -s "usr_%{version}_${usr_verity_part_uuid}.verity" '%{install-root}/usr.verity'

build-depends:
- external/cryptsetup
- external/squashfs-tools
release: 2
