id: modemmanager
version: 1.24.2
about: A unified high level API for communicating with mobile broadband modems, regardless of the protocol used to communicate with the actual device

variables:
  run-autogen: false
  seperate-build-dir: false

configure: >-
  --with-systemd-journal
  --with-systemd-suspend-resume
  --without-mbim
  --without-qmi
  --disable-static

depends:
  - libgudev
  - polkit

build-depends:
  - gobject-introspection
  - vala
  - gtk-doc

sources:
  - https://www.freedesktop.org/software/ModemManager/ModemManager-%{version}.tar.xz
