id: highway
version: 1.4.0
about: A C++ library that provides portable SIMD/vector intrinsics

build-type: cmake

configure: >-
  -D BUILD_TESTING=OFF
  -D BUILD_SHARED_LIBS=ON

depends:
    - glibc

build-depends:
    - cmake

sources:
    - https://github.com/google/highway/archive/%{version}/highway-%{version}.tar.gz
