[Transfer]
ProtectVersion=%A
Verify=false

[Source]
Type=url-file
Path=@UPDATE_URL@
MatchPattern=rlxos_@v.efi.xz

[Target]
Type=regular-file
Path=/EFI/Linux
PathRelativeTo=boot
MatchPattern=rlxos_@v+@l-@d.efi \
             rlxos_@v+@l.efi    \
             rlxos_@v.efi

Mode=0644
TriesLeft=3
TriesDone=0
InstancesMax=2
