id: xev
version: 1.2.6
about: Print contents of X events

depends:
  - libx11
  - libxrandr
build-depends:
  - util-macros
  - xorgproto
sources:
  - https://www.x.org/pub/individual/app/xev-%{version}.tar.xz

