id: libxcb
version: 1.17.0
about: X11 client-side library

pre-script: rm autogen.sh

sources:
  - https://www.x.org/pub/individual/lib/libxcb-%{version}.tar.xz

depends:
  - libxau
  - libxdmcp
  - xcb-proto

build-depends:
  - libxslt
  - python
  - pkg-config
  - util-macros
