id: cpio
version: 2.15
about: A tool to copy files into or out of a cpio or tar archive

pre-script: |-
  sed -e "/^extern int (\*xstat)/s/()/(const char * restrict,  struct stat * restrict)/" \
      -i src/extern.h
  sed -e "/^int (\*xstat)/s/()/(const char * restrict,  struct stat * restrict)/" \
      -i src/global.c

depends:
  - glibc

sources:
  - https://ftp.gnu.org/gnu/cpio/cpio-%{version}.tar.gz
