id: libxcrypt
version: 4.5.2
about: Modern library for one-way hashing of passwords

pre-script: |-

configure: >-
  --disable-static
  --enable-hashes=strong,glibc
  --enable-obsolete-api=glibc
  --disable-failure-tokens

depends:
  - glibc
sources:
  - https://github.com/besser82/libxcrypt/releases/download/v%{version}/libxcrypt-%{version}.tar.xz
  - external/libxcrypt/0001-libxcrypt-workspace.patch
