id: sway
version: 1.11
about: Tiling Wayland compositor and replacement for the i3 window manager

pre-script: |-
  sed -i "s/branch \\\'@1@\\\'/rlxos/g" meson.build
post-script: |-
  install -v -D -m 0644 /dev/stdin %{install-root}%{datadir}/xdg-desktop-portal/sway-portals.conf << "EOF"
  [preferred]
  default=gtk
  org.freedesktop.impl.portal.ScreenCast=wlr
  org.freedesktop.impl.portal.Screenshot=wlr
  EOF

  install -v -D -m 0644 LICENSE -t %{install-root}%{datadir}/doc/%{id}/

  rm -rf %{install-root}%{sysconfdir}/sway
  cp -rf /external/sway %{install-root}%{sysconfdir}/

configure: >-
  -D sd-bus-provider=libsystemd
  -D werror=false
  -D b_ndebug=true

depends:
  - cairo
  - gdk-pixbuf
  - libevdev
  - libinput
  - json-c
  - systemd
  - wayland
  - wlroots
  - libxcb
  - libxkbcommon
  - pango
  - pcre
  - seatd
build-depends:
  - meson
  - ninja
  - scdoc
  - setconf
  - wayland-protocols
sources:
  - https://github.com/swaywm/sway/releases/download/%{version}/sway-%{version}.tar.gz
