id: libXvMC
version: 1.0.15
about: X11 Video Motion Compensation extension library

build-type: autotools
configure: >-
  --disable-static

depends:
  - libx11
  - libxext
  - libxv

sources:
  - https://www.x.org/pub/individual/lib/libXvMC-%{version}.tar.xz
