id: mkinitramfs
version: 0.1.6
about: Script to build initramfs
depends:
  - glibc
  - procps-ng
  - lvm2
  - busybox
  - cpio
  - zstd
  - psmisc

script: |-
  install -v -D -m 644 /external/initramfs/init.in  %{install-root}/%{datadir}/initramfs/init.in
  install -v -D -m 755 /external/initramfs/mkinitramfs.sh.in  %{install-root}/%{bindir}/mkinitramfs
