id: python-setuptools-scm
version: 10.0.5
about: Package is used to extract Python package versions from git or hg metadata instead of declaring them

depends:
  - python

build-depends:
  - python-vcs-versioning
  - python-build
  - python-installer

sources:
  - https://files.pythonhosted.org/packages/source/s/setuptools_scm/setuptools_scm-%{version}.tar.gz
