// Code generated by genapi from dev.avyos.dbg. DO NOT EDIT.
package dbg

import (
	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
	"net"
)

// Client holds connections to all objects in the dev.avyos.dbg service.
type Client struct {
	conn *sutra.Conn
	Dbg  *DbgClient
}

// Connect dials the dev.avyos.dbg service over a Unix socket.
func Connect() (*Client, error) {
	nc, err := net.Dial("unix", fs.Resolve("service:dev.avyos.dbg"))
	if err != nil {
		return nil, err
	}
	conn := sutra.NewConn(nc)
	return &Client{
		conn: conn,
		Dbg:  NewDbgClient(conn, 0),
	}, nil
}

// HandleEvent dispatches an incoming event to the appropriate object client.
func (cl *Client) HandleEvent(tx sutra.Transaction) error {
	return sutra.DispatchEvent(tx, cl.Dbg)
}

// Close closes the underlying connection.
func (cl *Client) Close() error {
	return cl.conn.Close()
}

type DbgClient struct {
	Conn        *sutra.Conn
	Object      uint32
	shellExit   func(args ShellExitEvent)
	shellOutput func(args ShellOutputEvent)
}

func NewDbgClient(conn *sutra.Conn, object uint32) *DbgClient {
	return &DbgClient{Conn: conn, Object: object}
}

func (c *DbgClient) OnShellExit(fn func(args ShellExitEvent)) {
	c.shellExit = fn
}

func (c *DbgClient) OnShellOutput(fn func(args ShellOutputEvent)) {
	c.shellOutput = fn
}

func (c *DbgClient) HandleEvent(tx sutra.Transaction) (bool, error) {
	if tx.Object != c.Object {
		return false, nil
	}
	switch tx.Event {
	case OpDbgShellExit:
		if c.shellExit != nil {
			args, err := sutra.UnmarshalPayload[ShellExitEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.shellExit(args)
		}
		return true, nil
	case OpDbgShellOutput:
		if c.shellOutput != nil {
			args, err := sutra.UnmarshalPayload[ShellOutputEvent](tx.Payload)
			if err != nil {
				return true, err
			}
			c.shellOutput(args)
		}
		return true, nil
	}
	return false, nil
}

func (c *DbgClient) Authenticate(in AuthRequest) (SessionInfo, error) {
	var zero SessionInfo
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgAuthenticate, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[SessionInfo](resp.Payload)
}

func (c *DbgClient) Logout(in SessionToken) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgLogout, Payload: payload})
	return err
}

func (c *DbgClient) ReadFile(in ReadFileRequest) (FileChunk, error) {
	var zero FileChunk
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgReadFile, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[FileChunk](resp.Payload)
}

func (c *DbgClient) RunCommand(in ExecRequest) (ExecResult, error) {
	var zero ExecResult
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgRunCommand, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ExecResult](resp.Payload)
}

func (c *DbgClient) RunShell(in ExecRequest) (ExecResult, error) {
	var zero ExecResult
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgRunShell, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ExecResult](resp.Payload)
}

func (c *DbgClient) ShellClose(in ShellCloseRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgShellClose, Payload: payload})
	return err
}

func (c *DbgClient) ShellInput(in ShellInputRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgShellInput, Payload: payload})
	return err
}

func (c *DbgClient) ShellOpen(in ShellOpenRequest) (ShellSession, error) {
	var zero ShellSession
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgShellOpen, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[ShellSession](resp.Payload)
}

func (c *DbgClient) ShellResize(in ShellResizeRequest) error {
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return err
	}
	_, err = c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgShellResize, Payload: payload})
	return err
}

func (c *DbgClient) WriteFile(in WriteFileRequest) (WriteFileResult, error) {
	var zero WriteFileResult
	payload, err := sutra.MarshalPayload(in)
	if err != nil {
		return zero, err
	}
	resp, err := c.Conn.SendRecv(sutra.Transaction{Object: c.Object, Event: OpDbgWriteFile, Payload: payload})
	if err != nil {
		return zero, err
	}
	return sutra.UnmarshalPayload[WriteFileResult](resp.Payload)
}
