// Code generated by genapi from dev.avyos.dbg. DO NOT EDIT.
package dbg

import (
	"avyos.dev/lib/sutra"
	"fmt"
	"net"
)

type DbgHandler interface {
	Authenticate(object uint32, in AuthRequest) (SessionInfo, error)
	Logout(object uint32, in SessionToken) error
	ReadFile(object uint32, in ReadFileRequest) (FileChunk, error)
	RunCommand(object uint32, in ExecRequest) (ExecResult, error)
	RunShell(object uint32, in ExecRequest) (ExecResult, error)
	ShellClose(object uint32, in ShellCloseRequest) error
	ShellInput(object uint32, in ShellInputRequest) error
	ShellOpen(object uint32, in ShellOpenRequest) (ShellSession, error)
	ShellResize(object uint32, in ShellResizeRequest) error
	WriteFile(object uint32, in WriteFileRequest) (WriteFileResult, error)
}

type Handlers struct {
	Dbg DbgHandler
}

func Dispatch(h Handlers, conn *sutra.Conn, tx sutra.Transaction) error {
	switch tx.Event {
	case OpDbgAuthenticate:
		in, err := sutra.UnmarshalPayload[AuthRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.Authenticate: %w", err)
		}
		out, err := h.Dbg.Authenticate(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Dbg.Authenticate: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDbgLogout:
		in, err := sutra.UnmarshalPayload[SessionToken](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.Logout: %w", err)
		}
		if err := h.Dbg.Logout(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDbgReadFile:
		in, err := sutra.UnmarshalPayload[ReadFileRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.ReadFile: %w", err)
		}
		out, err := h.Dbg.ReadFile(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Dbg.ReadFile: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDbgRunCommand:
		in, err := sutra.UnmarshalPayload[ExecRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.RunCommand: %w", err)
		}
		out, err := h.Dbg.RunCommand(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Dbg.RunCommand: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDbgRunShell:
		in, err := sutra.UnmarshalPayload[ExecRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.RunShell: %w", err)
		}
		out, err := h.Dbg.RunShell(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Dbg.RunShell: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDbgShellClose:
		in, err := sutra.UnmarshalPayload[ShellCloseRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.ShellClose: %w", err)
		}
		if err := h.Dbg.ShellClose(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDbgShellInput:
		in, err := sutra.UnmarshalPayload[ShellInputRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.ShellInput: %w", err)
		}
		if err := h.Dbg.ShellInput(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDbgShellOpen:
		in, err := sutra.UnmarshalPayload[ShellOpenRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.ShellOpen: %w", err)
		}
		out, err := h.Dbg.ShellOpen(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Dbg.ShellOpen: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	case OpDbgShellResize:
		in, err := sutra.UnmarshalPayload[ShellResizeRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.ShellResize: %w", err)
		}
		if err := h.Dbg.ShellResize(tx.Object, in); err != nil {
			return err
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event})
	case OpDbgWriteFile:
		in, err := sutra.UnmarshalPayload[WriteFileRequest](tx.Payload)
		if err != nil {
			return fmt.Errorf("decode Dbg.WriteFile: %w", err)
		}
		out, err := h.Dbg.WriteFile(tx.Object, in)
		if err != nil {
			return err
		}
		payload, err := sutra.MarshalPayload(out)
		if err != nil {
			return fmt.Errorf("encode Dbg.WriteFile: %w", err)
		}
		return conn.Send(sutra.Transaction{Object: tx.Object, Event: tx.Event, Payload: payload})
	default:
		return fmt.Errorf("unknown opcode: %d", tx.Event)
	}
}

func SendDbgShellExit(conn *sutra.Conn, object uint32, args ShellExitEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDbgShellExit, Payload: payload})
}

func SendDbgShellOutput(conn *sutra.Conn, object uint32, args ShellOutputEvent) error {
	payload, err := sutra.MarshalPayload(args)
	if err != nil {
		return err
	}
	return conn.Send(sutra.Transaction{Object: object, Event: OpDbgShellOutput, Payload: payload})
}

// Server listens on the dev.avyos.dbg Unix socket and dispatches incoming requests.
type Server struct {
	Handlers
	ln net.Listener
}

// Listen creates the dev.avyos.dbg Unix socket and returns a Server ready to serve.
func Listen() (*Server, error) {
	ln, err := net.Listen("unix", "/run/dev.avyos.dbg")
	if err != nil {
		return nil, err
	}
	return &Server{ln: ln}, nil
}

// Serve accepts connections and dispatches each transaction in a goroutine.
// It blocks until Close is called or a fatal accept error occurs.
func (s *Server) Serve() error {
	for {
		nc, err := s.ln.Accept()
		if err != nil {
			return err
		}
		go s.serveConn(nc)
	}
}

func (s *Server) serveConn(nc net.Conn) {
	conn := sutra.NewConn(nc)
	defer conn.Close()
	for {
		tx, err := conn.Recv()
		if err != nil {
			return
		}
		if err := Dispatch(s.Handlers, conn, tx); err != nil {
			return
		}
	}
}

// Close stops the listener.
func (s *Server) Close() error {
	return s.ln.Close()
}
