// Code generated by genapi from dev.avyos.dbg. DO NOT EDIT.
package dbg

type AuthRequest struct {
	Password string
	Username string
}

type ExecRequest struct {
	Command    string
	Cwd        string
	TimeoutSec int32
	Token      string
}

type ExecResult struct {
	ExitCode        int32
	Stderr          []byte
	StderrTruncated uint8
	Stdout          []byte
	StdoutTruncated uint8
}

type FileChunk struct {
	Data []byte
	Eof  uint8
}

type ReadFileRequest struct {
	Offset uint64
	Path   string
	Size   uint32
	Token  string
}

type SessionInfo struct {
	GID      uint32
	Home     string
	Shell    string
	Token    string
	UID      uint32
	Username string
}

type SessionToken struct {
	Token string
}

type ShellCloseRequest struct {
	SessionID uint32
	Token     string
}

type ShellExitEvent struct {
	ExitCode  int32
	SessionID uint32
}

type ShellInputRequest struct {
	Data      []byte
	SessionID uint32
	Token     string
}

type ShellOpenRequest struct {
	Cols  int32
	Cwd   string
	Rows  int32
	Token string
}

type ShellOutputEvent struct {
	Data      []byte
	SessionID uint32
}

type ShellResizeRequest struct {
	Cols      int32
	Rows      int32
	SessionID uint32
	Token     string
}

type ShellSession struct {
	SessionID uint32
}

type WriteFileRequest struct {
	Data     []byte
	Mode     uint32
	Offset   uint64
	Path     string
	Token    string
	Truncate uint8
}

type WriteFileResult struct {
	Written uint32
}

const (
	OpDbgAuthenticate uint16 = 1
	OpDbgLogout       uint16 = 2
	OpDbgReadFile     uint16 = 3
	OpDbgRunCommand   uint16 = 4
	OpDbgRunShell     uint16 = 5
	OpDbgShellClose   uint16 = 6
	OpDbgShellInput   uint16 = 7
	OpDbgShellOpen    uint16 = 8
	OpDbgShellResize  uint16 = 9
	OpDbgWriteFile    uint16 = 10
	OpDbgShellExit    uint16 = 11
	OpDbgShellOutput  uint16 = 12
)
