// Code generated by apigen. DO NOT EDIT.

package main

import (
	"errors"
	"io"

	api "avyos.dev/api/init"
	"avyos.dev/pkg/connect"
)

var ErrUnknownEvent = errors.New("unknown event")

type InitServer struct {
	impl *Init
}

func startInitServer(impl *Init) error {
	conn, err := connect.SystemBus()
	if err != nil {
		return err
	}

	if err := conn.Register(api.ObjectId); err != nil {
		return err
	}

	s := &InitServer{impl: impl}

	for {
		m, err := conn.Recieve()
		if err != nil {
			if err == io.EOF {
				return nil
			}
			continue
		}
		out, err := s.Dispatch(m.Event, m.Payload)
		if err != nil {
			conn.Send(connect.Message{
				Sender:      api.ObjectId,
				Destination: m.Sender,
				Event:       connect.BusErrorEvent,
				Payload:     []byte(err.Error()),
			})
			continue
		}

		conn.Send(connect.Message{
			Sender:      api.ObjectId,
			Destination: m.Sender,
			Event:       connect.BusReplyEvent,
			Payload:     out,
		})
	}
}

func (s *InitServer) Dispatch(event uint16, payload []byte) ([]byte, error) {
	switch event {
	case api.ListEvent:
		return s.handleList(payload)
	case api.StatusEvent:
		return s.handleStatus(payload)
	default:
		return nil, ErrUnknownEvent
	}
}

func (s *InitServer) handleList(payload []byte) ([]byte, error) {
	in, err := connect.Decode[string](payload)
	if err != nil {
		return nil, err
	}

	out, err := s.impl.List(in)

	if err != nil {
		return nil, err
	}
	return connect.Encode(out)
}

func (s *InitServer) handleStatus(payload []byte) ([]byte, error) {
	in, err := connect.Decode[string](payload)
	if err != nil {
		return nil, err
	}

	out, err := s.impl.Status(in)

	if err != nil {
		return nil, err
	}
	return connect.Encode(out)
}
