id: libxrandr
version: 1.5.5
about: xorg library libXrandr

sources:
  - https://www.x.org/pub/individual/lib/libXrandr-%{version}.tar.xz

depends:
  - libxext
  - libxrender

build-depends:
  - util-macros
  - xorgproto
