id: libksba
version: 1.7.0
about: A library used to make X.509 certificates as well as making the CMS

depends:
  - libgpg-error
sources:
  - https://www.gnupg.org/ftp/gcrypt/libksba/libksba-%{version}.tar.bz2
